// backgrounddata.js
const backgroundData = {
    backgrounds: [
'backgrounds/Gemini_7ekkij7ekkij7ekk.png',
'backgrounds/Gemini_7ekkik7ekkik7ekk.png',
'backgrounds/Gemini_7ekkil7ekkil7ekk.png',
'backgrounds/Gemini_7ekkim7ekkim7ekk.png',
'backgrounds/Gemini_7ekkio7ekkio7ekk.png',
'backgrounds/Gemini_7ekkis7ekkis7ekk.png',
'backgrounds/Gemini_kubxpvkubxpvkubx.png',
'backgrounds/Gemini_kubxpxkubxpxkubx.png',
'backgrounds/Gemini_kubxpykubxpykubx.png',
'backgrounds/Gemini_kubxpzkubxpzkubx.png',
'backgrounds/Gemini_kubxq3kubxq3kubx.png',
'backgrounds/Gemini_ni3c9nni3c9nni3c.png',
'backgrounds/Gemini_ni3c9oni3c9oni3c.png',
'backgrounds/Gemini_ni3c9pni3c9pni3c.png',
'backgrounds/Gemini_ni3c9qni3c9qni3c.png',
'backgrounds/Gemini_ni3c9rni3c9rni3c.png',
'backgrounds/Gemini_ni3c9sni3c9sni3c.png',
'backgrounds/Gemini_ni3c9vni3c9vni3c.png',
'backgrounds/Gemini_ufa1qzufa1qzufa1.png',
'backgrounds/Gemini_ufa1r0ufa1r0ufa1.png',
'backgrounds/Gemini_ufa1r1ufa1r1ufa1.png',
'backgrounds/Gemini_ufa1r2ufa1r2ufa1.png',
'backgrounds/Gemini_ufa1r3ufa1r3ufa1.png',
'backgrounds/Gemini_ufa1r4ufa1r4ufa1.png',
'backgrounds/Gemini_ufa1r5ufa1r5ufa1.png',
'backgrounds/Gemini_ufa1r6ufa1r6ufa1.png',
'backgrounds/Gemini_ufa1r8ufa1r8ufa1.png',
'backgrounds/Gemini_ul9slnul9slnul9s.png',
'backgrounds/Gemini_ul9sloul9sloul9s.png',
'backgrounds/Gemini_ul9slqul9slqul9s.png',
'backgrounds/Gemini_ul9slrul9slrul9s.png',
'backgrounds/Gemini_ul9slsul9slsul9s.png',
'backgrounds/Gemini_ul9sluul9sluul9s.png',
'backgrounds/Gemini_ul9slwul9slwul9s.png',

        // add more background images here
    ]
};
